ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS details JSONB DEFAULT NULL;
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS akteur VARCHAR(10) NOT NULL DEFAULT 'USER' CHECK (akteur IN ('USER', 'SYSTEM'));
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS kontext TEXT DEFAULT NULL;
ALTER TABLE schadensfaelle ADD COLUMN IF NOT EXISTS storniert_am TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE schadensfaelle ADD COLUMN IF NOT EXISTS storniert_von UUID REFERENCES benutzer(id) ON DELETE SET NULL DEFAULT NULL;
ALTER TABLE schadensfaelle ADD COLUMN IF NOT EXISTS stornierungsgrund TEXT DEFAULT NULL;
